# News Headline Classification Using Naive Bayes....

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [3]:
df = pd.read_csv('news_data-2.csv')

In [27]:
df.head()

headline    category
0  Porn star jokes she could post nudes on Insta ...  technology
1  Satellite pics show remains of SpaceX's rocket...  technology
2  Not in favour of recommending such games: Top ...  technology
3  Researchers develop first AI tool to detect CO...  technology
4  Virgin Galactic's test space flight cut short ...  technology

In [5]:
df.shape

(1563, 4)

In [6]:
df.columns.unique()

Index(['Unnamed: 0', 'news_headline', 'news_article', 'news_category'], dtype='object')

In [7]:
df.drop(['Unnamed: 0'], axis=1, inplace = True)

In [8]:
df.drop(['news_article'], axis=1, inplace = True)

In [9]:
df.head()

news_headline news_category
0  Porn star jokes she could post nudes on Insta ...    technology
1  Satellite pics show remains of SpaceX's rocket...    technology
2  Not in favour of recommending such games: Top ...    technology
3  Researchers develop first AI tool to detect CO...    technology
4  Virgin Galactic's test space flight cut short ...    technology

In [10]:
df.isnull().sum()

news_headline    0
news_category    0
dtype: int64

In [11]:
df['news_category'].value_counts()

technology       225
sports           225
politics         225
science          225
world            223
entertainment    222
automobile       218
Name: news_category, dtype: int64

In [12]:
df_cols = ['headline', 'category']

In [13]:
df.columns = df_cols

In [14]:
df.head()

headline    category
0  Porn star jokes she could post nudes on Insta ...  technology
1  Satellite pics show remains of SpaceX's rocket...  technology
2  Not in favour of recommending such games: Top ...  technology
3  Researchers develop first AI tool to detect CO...  technology
4  Virgin Galactic's test space flight cut short ...  technology

# Now separate data into train test split(70% train and 30% test)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split as tts
from sklearn.naive_bayes import MultinomialNB

In [16]:
x = df['headline']
y = df['category']
cv = CountVectorizer()
X = cv.fit_transform(x)


In [17]:
cv.get_feature_names_out()

array(['00', '000', '01', ..., 'zoom', 'zoox', 'zuckerberg'], dtype=object)

In [18]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.33, random_state=42)

In [20]:
X_train

<1047x3122 sparse matrix of type '<class 'numpy.int64'>'
	with 11582 stored elements in Compressed Sparse Row format>

In [21]:
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [26]:
user = input("Enter a Text: ")
data = cv.transform([user]).toarray()
output = model.predict(data)
print(output)

Enter a Text: India must continue with their aggr ..  Read more at: http://timesofindia.indiatimes.com/articleshow/93733887.cms?utm_source=contentofinterest&utm_medium=text&utm_campaign=cppst
['sports']
